### ISSUE TITLE
Maindest merge issue

### ISSUE THREAD

**Issue by pradeepmdk** [Pocket-titan/react-native-whatsapp-stickers-android#1]
Task :app:processDebugManifest FAILED
/home/pradeep/Documents/react/mobile/AwesomeProject/android/app/src/main/AndroidManifest.xml:12:9-17:66 Error:
        Attribute provider#com.whatsapp_stickers.stickers.StickerContentProvider@authorities at AndroidManifest.xml:12:9-17:66 requires a placeholder substitution but no value for <contentProviderAuthority> is provided.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute provider#com.whatsapp_stickers.stickers.StickerContentProvider@authorities at AndroidManifest.xml:12:9-17:66 requires a placeholder substitution but no value for <contentProviderAuthority> is provided.

**Comment by Pocket-titan** [comment]
Hi @kongupradeep,

Please take a look at the newest pull request. I forgot a variable definition in the `build.gradle` of your app that needs to be added, which is now under step 3 of the readme.
If the issue persists, feel free to reopen this issue.
